### ISSUE TITLE
Compatibilty With Karbonn TItanium Octane

### ISSUE THREAD

**Issue by vivekkiran** [Ritzythedevil/TWRP_OctanePlus#8]
Will this Work with Karbonn Titanium Octane .

**Comment by ritesh-jain** [comment]
No, only for octane plus.

**Comment by vivekkiran** [comment]
ok, is there any thing I can do or modify to make it work with octane.

**Comment by ritesh-jain** [comment]
Go to this thread - 
http://forum.xda-developers.com/showthread.php?t=2798257

Follow the instructions. If u need any help, u can ask.
